#! /bin/bash

OPT="$1"
GP="$(echo $2 | cut -d. -f1)"
FLD="$(echo $2 | cut -d. -f2)"
VAL="$3"

# Only proceed if arguments make sense.
[[ ( $OPT == "--get" || $OPT == "--unset" || ( $OPT == "--set" && $VAL ) )  && $GP && $FLD ]] || {
    echo "Usage: $0 --set [GROUP].[FIELD] [VALUE]"
    echo "       $0 --get [GROUP].[FIELD]"
    exit 1
}

function sgit_config_set() {
    tgt_file="$1"
    group="$2"
    field="$3"
    value="$4"
    insert_text="$field = $value"
    sed -i '/\['"$group"'\]/a\    '"$insert_text" "$tgt_file"
}

function sgit_config_get() { :
    tgt_file="$1"
    group="$2"
    field="$3"
    awk '/^\[/ {p=0} /^\['"$group"'\]/ {p=1} p' "$tgt_file" | grep "$field" | sed 's/^[[:space:]]*'"$field"'[[:space:]]*=[[:space:]]*//g'
}

function sgit_config_unset() { :
    tgt_file="$1"
    group="$2"
    field="$3"
    sed -i '/^\['"$group"'\]/,/^\[/ {/^[[:space:]]*'"$field"'/d}' "$tgt_file"
}

cfg_file=~/.gitconfig
case $OPT in
    --get) sgit_config_get "$cfg_file" "$GP" "$FLD" ;;
    --set) sgit_config_set "$cfg_file" "$GP" "$FLD" "$VAL" ;;
    --unset) sgit_config_unset "$cfg_file" "$GP" "$FLD" ;;
esac
